# Edgerouter/VyOS management scripts
# Copyright (c) 2024 Jackson Tong, Creekside Networks LLC.
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

import  os
import json

DEFAULT_IPSEC_SECRETS = f"""
: RSA "/config/ipsec.d/certs/server.key"
"""

class IPSecSecrets:
    def __init__(self):
        self.secrets = {}

    def loads(self, ipsec_secrets_str):
        self.secrets = {}
        ipsec_secrets_lines = ipsec_secrets_str.split('\n')

        for line in ipsec_secrets_lines:
            line = line.strip()
            if not line or line.startswith('#') or line.startswith('include'):
                continue

            if ':' in line:
                id, key_value = line.split(':', 1)
                key, value      = key_value.strip().split(' ', 1)

                id      = id.strip()
                key     = key.strip()
                value   = value.strip().strip('"')

                #print(f"{id} | {key} | {value}")
                if key in ['RSA']:
                    if key not in self.secrets:
                        self.secrets[key] = [value]
                    else:
                        self.secrets[key].append(value)
                elif key in ['PSK', 'EAP']:
                    if key not in self.secrets:
                        self.secrets[key] = {}
                    self.secrets[key][id] = value                            
            else:
                print(f"\n   *** Invalid key-value pair: {line}")

        #print (json.dumps(self.secrets, indent=4))
        return self.secrets

    def dumps(self):
        from datetime import datetime

        # Format the timestamp
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Add the timestamp to the string
        ipsec_secrets_str = f"#\n# IPSec.secrets generated by Creekside Networks LLC on {timestamp}\n#\n"

        for key, value in self.secrets.items():
            if key == 'RSA':
                for rsa_key in value:
                    ipsec_secrets_str += f"{' ' * 32} : {key} \"{rsa_key}\"\n"
            elif key in ['PSK', 'EAP']:
                # Add sample commented user for EAP
                if key == 'EAP' and len(value) == 0:
                    ipsec_secrets_str += f"#test{' ' * 28}: {key} \"test123\"\n"
                for id, secret in value.items():
                    ipsec_secrets_str += f"{id:32s} : {key} \"{secret}\"\n"
            ipsec_secrets_str += '\n'

        return ipsec_secrets_str
    
    def get(self, key):
        if key in self.secrets:
            return self.secrets[key]
        else:
            return None